### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mikecoux** [learn-co-curriculum/python-p4-adding-react-to-flask#1]
### Canvas Link

https://learning.flatironschool.com/courses/6330/assignments/239795?module_item_id=563990

### Concern

When reviewing the useEffect in app.js the lab says you can add a conditional to check for a 200 response by returning 'r.json'

this conditional is missing '()' after .json

### Additional Context

<img width="474" alt="Screenshot 2023-05-25 at 10 53 00 AM" src="https://github.com/learn-co-curriculum/python-p4-adding-react-to-flask/assets/100630883/96bf9632-0e8b-49b3-bdd3-f780484eeb17">

**Comment by linda-seiter** [comment]
typo fixed
