### ISSUE TITLE
Issue with Flask SQLAlchemy versions in pipenv

### ISSUE THREAD

**Issue by rae-stanton** [learn-co-curriculum/python-p4-adding-react-to-flask#3]
### Canvas Link

https://learning.flatironschool.com/courses/6813/assignments/257017?module_item_id=608056

### Concern

Hello there! This walkthrough in particular has out of date versions for SQLAlchemy when running `pipenv` - the temporary solution is to run `pip install Flask-SQLAlchemy --upgrade`, but the version needs to be updated in the `pipfile`.  
Currently, this is the version in some of the `Pipfile`s throughout the course:

```
flask-sqlalchemy = "3.0.2"
```

The temporary solution basically removed the specificity for version control, but I believe the current version should be `3.1.1`, and it's likely the version a lot of us are using globally. Without the upgrade, the issue of not being able to implement database commands has popped up for a lot of us.

```
flask-sqlalchemy = "*"
```

Thanks in advance for taking a look at this! 😊

### Additional Context

<img width="1420" alt="Screenshot 2023-10-06 at 9 21 22 AM" src="https://github.com/learn-co-curriculum/python-p4-adding-react-to-flask/assets/101673900/4cbe0932-8faa-49bd-8993-0ffeed37d5a5">
Here's a screenshot for context.

### Suggested Changes

Updating version numbers in relevant `Pipfiles` to match the most recent version numbers will likely fix the issue.

**Comment by linda-seiter** [comment]
pipfiles updated in all phase 4 repos
